"""Only a uv-generated closure may skip resolution; everything else resolves."""
from __future__ import annotations

from scripts.requirements_closure import classify, main

HEADER = "# This file was autogenerated by uv via the following command:\n"
COMPILE = "#    uv pip compile app/requirements.in -o app/requirements.txt --universal\n"

CLOSURE = HEADER + COMPILE + """\
annotated-doc==0.0.5
    # via fastapi
cffi==2.1.1 ; platform_python_implementation != 'PyPy'
uvicorn[standard]==0.38.0
soev-inference @ git+https://github.com/Gradient-DS/soev-agents.git@79cf3e15#subdirectory=packages/soev-inference
    # via -r app/requirements.in
"""


def test_uv_compile_output_is_a_closure():
    assert classify(CLOSURE)[0] == "no-deps"


def test_uv_export_output_is_a_closure():
    text = (HEADER + "#    uv export --format requirements-txt --no-emit-project --no-hashes\n"
            "-e ./packages/soev-inference\n    # via soev-agents\nhttpx==0.28.1\n")
    assert classify(text)[0] == "no-deps"


def test_hashed_continuation_lines_are_one_requirement():
    text = HEADER + COMPILE + "idna==3.10 \\\n    --hash=sha256:aa \\\n    --hash=sha256:bb\n"
    assert classify(text)[0] == "no-deps"


def test_hand_written_pins_are_not_a_closure():
    """`==` pins of direct dependencies only: --no-deps would skip every transitive one."""
    assert classify("fastapi==0.115.0\nhttpx==0.28.1\n") == ("resolve", "not uv pip compile output")


def test_header_must_be_the_first_line():
    assert classify("# my notes\n" + CLOSURE)[0] == "resolve"


def test_compiled_with_no_deps_is_not_a_closure():
    text = HEADER + "#    uv pip compile req.in --no-deps\nhttpx==0.28.1\n"
    assert classify(text) == ("resolve", "compiled with --no-deps")


def test_compiled_without_a_package_is_not_a_closure():
    text = HEADER + "#    uv pip compile req.in --no-emit-package=torch\nhttpx==0.28.1\n"
    assert classify(text)[0] == "resolve"


def test_hand_edited_range_falls_back_to_resolving():
    assert classify(CLOSURE + "requests>=2\n")[0] == "resolve"


def test_include_line_falls_back_to_resolving():
    assert classify(CLOSURE + "-r other.txt\n")[0] == "resolve"


def test_main_prints_mode_path_reason(tmp_path, capsys):
    closed = tmp_path / "a.txt"
    closed.write_text(CLOSURE)
    loose = tmp_path / "b.txt"
    loose.write_text("httpx\n")
    assert main([str(closed), str(loose)]) == 0
    out = capsys.readouterr().out.splitlines()
    assert out == [f"no-deps\t{closed}\tuv-generated closure", f"resolve\t{loose}\tnot uv pip compile output"]
