"""Decide which requirements files pip-audit may audit without resolving.

pip-audit's default is to install a file into a scratch venv (`pip install
--dry-run`) and audit what pip resolved. For a file that already lists its full
dependency closure, `--no-deps --disable-pip` audits the same packages from
the file itself, in seconds instead of minutes.

Only one shape of file is trusted to be a closure: `uv pip compile` output,
recognised by its header, whose command line drops nothing from the closure
and whose every requirement is pinned with `==` (or is a URL/editable
requirement, which neither mode can audit and both report as skipped). A
hand-written file of `==` pins is NOT a closure — it pins the direct
dependencies only, and `--no-deps` would silently skip every transitive one —
so anything else keeps being resolved.

Prints one line per file, `<mode>\t<path>\t<reason>`, mode `no-deps` or
`resolve`.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

UV_HEADER = "# This file was autogenerated by uv via the following command:"

# Compile options after which the file is no longer the full closure, so
# auditing it without resolving would miss packages a resolve would find.
CLOSURE_BREAKING_OPTIONS = ("--no-deps", "--no-emit-package", "--no-emit-workspace", "--prune")

# `name[extras]==version`, optionally followed by an environment marker.
PINNED = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(\[[A-Za-z0-9._,-]+\])?==[^\s;=<>!~]+(\s*;.*)?$")
# `name[extras] @ <url>`, optionally followed by an environment marker.
URL_REQ = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(\[[A-Za-z0-9._,-]+\])?\s*@\s*\S+(\s*;.*)?$")


def _logical_lines(text: str) -> list[str]:
    """Join backslash continuations and strip comments."""
    joined = re.sub(r"\\\n", " ", text)
    out = []
    for line in joined.splitlines():
        line = re.sub(r"(^|\s)#.*$", "", line).strip()
        if line:
            out.append(line)
    return out


def classify(text: str) -> tuple[str, str]:
    """Return (mode, reason) for one requirements file's content."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != UV_HEADER:
        return "resolve", "not uv pip compile output"
    command = lines[1].lstrip("#").strip() if len(lines) > 1 else ""
    if not command.startswith("uv "):
        return "resolve", "uv header without a uv command line"
    for option in CLOSURE_BREAKING_OPTIONS:
        if re.search(rf"(^|\s){re.escape(option)}(=|\s|$)", command):
            return "resolve", f"compiled with {option}"
    for line in _logical_lines(text):
        # Hashes ride on the requirement they follow; strip them before matching.
        req = re.sub(r"\s--hash[= ]\S+", "", " " + line).strip()
        if req.startswith("-e ") or req.startswith("--editable "):
            continue
        if req.startswith("-"):
            return "resolve", f"option line {req.split()[0]!r}"
        if not (PINNED.match(req) or URL_REQ.match(req)):
            return "resolve", f"unpinned requirement {req!r}"
    return "no-deps", "uv-generated closure"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("files", nargs="+", type=Path)
    args = parser.parse_args(argv)
    for path in args.files:
        mode, reason = classify(path.read_text(encoding="utf-8"))
        print(f"{mode}\t{path}\t{reason}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
